from pydantic import BaseModel, Field
from typing import List, Optional

class Citation(BaseModel):
    """
    A specific source reference pulled from a document to back up a claim.
    """
    document_id: str
    document_name: str
    page_number: int
    bbox: Optional[list[float]] = Field(
        default=None,
        description="Bounding box [x0, top, x1, bottom] of the source text/table"
    )
    content_hash: str = Field(
        ...,
        description="SHA-256 spatial and content hash from the Logical Document Unit (LDU)"
    )
    extracted_text: str = Field(description="The actual snippet of text that was retrieved.")

class ProvenanceChain(BaseModel):
    """
    Audit trail attached to any factual answer generated by the Query Agent.
    Every answer carries full provenance: page, bbox, content_hash, and the
    evidence_bundle_hash for reproducibility.
    """
    answer: str = Field(..., description="The generated factual answer to the user's query.")
    query_text: str = Field(default="", description="The original user query for audit traceability.")
    citations: List[Citation] = Field(
        default_factory=list,
        description="List of all sources used to generate this answer."
    )
    is_verifiable: bool = Field(
        default=True,
        description="Flag set to false if the model could not find citations to back its claim."
    )
    confidence_level: float = Field(
        default=0.0,
        description="System confidence in the answer (0.0–1.0), based on retrieval scores."
    )
    retrieval_method: str = Field(
        default="",
        description="Which tool(s) produced the evidence, e.g. 'hybrid_search+structured_query'."
    )
    evidence_bundle_hash: str = Field(
        default="",
        description="SHA256(query + sorted(chunk_content_hashes)) for reproducibility."
    )
