from pydantic import BaseModel, Field
from typing import List, Optional

class Citation(BaseModel):
    """
    A specific source reference pulled from a document to back up a claim.
    """
    document_id: str
    document_name: str
    page_number: int
    bbox: Optional[list[float]] = Field(
        default=None,
        description="Bounding box [x0, top, x1, bottom] of the source text/table"
    )
    content_hash: str = Field(
        ...,
        description="SHA-256 spatial and content hash from the Logical Document Unit (LDU)"
    )
    extracted_text: str = Field(description="The actual snippet of text that was retrieved.")

class ProvenanceChain(BaseModel):
    """
    Audit trail attached to any factual answer generated by the Query Agent.
    """
    answer: str = Field(..., description="The generated factual answer to the user's query.")
    citations: List[Citation] = Field(
        default_factory=list,
        description="List of all sources used to generate this answer."
    )
    is_verifiable: bool = Field(
        default=True,
        description="Flag set to false if the model could not find citations to back its claim (Audit Mode)"
    )
